# Generated by Django 3.1.5 on 2021-01-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210112_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
        migrations.AddField(
            model_name='chat',
            name='seen_by',
            field=models.ManyToManyField(related_name='seenby', to='chat.Contact'),
        ),
    ]
