# Generated by Django 3.1.5 on 2021-01-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210112_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='seen_by',
        ),
    ]
